server {
    listen 3000;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /predict {
        proxy_pass http://sentiment-ui:8000/predict;
        proxy_set_header Content-Type application/json;
    }

    location /chat {
        proxy_pass http://sentiment-ui:8000/chat;
        proxy_set_header Content-Type application/json;
    }
}